apiVersion: apps/v1
kind: Deployment
metadata:
  name: django-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: django
  template:
    metadata:
      labels:
        app: django
    spec:
      containers:
        - name: django-container
          image: "228266398439.dkr.ecr.us-east-1.amazonaws.com/lesson-5-ecr:latest"
          ports:
            - containerPort: 80
          envFrom:
            - configMapRef:
                name: django-config
          resources:
            requests:
              cpu: "100m"
              memory: "128Mi"
            limits:
              cpu: "200m"
              memory: "256Mi"