apiVersion: v1
kind: Secret
metadata:
  name: django-app-repository
  namespace: {{ .Release.Namespace }}
  labels:
    argocd.argoproj.io/secret-type: repository
type: Opaque
stringData:
  type: git
  url: {{ .Values.repository.url | quote }}
